[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=26.5.1",
    "dotenv>=0.9.9",
    "isort>=9.0.1",
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "langchain-ollama>=1.1.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
langchain-course = "langchain_course:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
